Rails.application.routes.draw do
  get "shoppers" => "shoppers#index"
  get "shoppers/new" => "shoppers#new"
  post "shoppers" => "shoppers#create"
  get "shoppers/:id/edit" => "shoppers#edit"
  post "shoppers/:id" => "shoppers#update"
  get "shoppers/:id/delete" => "shoppers#delete"
  delete "shoppers/:id" => "shoppers#destroy"
  get "lists" => "lists#index"
  get "lists/new" => "lists#new"
  post "lists" => "lists#create"
  get "lists/:id/edit" => "lists#edit"
  post "lists/:id" => "lists#update"
  get "lists/:id/delete" => "lists#delete"
  delete "lists/:id" => "lists#destroy"
  get "appearances" => "appearances#index"
  post "appearances" => "appearances#create"
  get "shoppers/:id" => "shoppers#show"
end